# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GerenteDeCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('cuentas', models.ManyToManyField(to='cuentas.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=20000, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='gerentedecuentas',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.PerfilEmpleado'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Localidad'),
        ),
    ]
